# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RN56Boilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RN56Boilerplate

  target 'RN56Boilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RN56BoilerplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RN56Boilerplate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RN56Boilerplate-tvOS

  # target 'RN56Boilerplate-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
